### ISSUE TITLE
[Bug] Compatibility Issue with Dynamic Mining

### ISSUE THREAD

**Issue by JuicyCosmos** [creep3rcrafter/Mystic-Potions#5]
When paired with [Dynamic Mining](https://legacy.curseforge.com/minecraft/mc-mods/dynamic-mining) it crashes the game when trying to mine blocks in survival. Removing this mod solves the issue.
This is the latest log:
[latest.log](https://github.com/creep3rcrafter/Mystic-Potions/files/12168106/latest.log)
and crash log:
[crash-2023-07-26_13.04.54-client.txt](https://github.com/creep3rcrafter/Mystic-Potions/files/12168113/crash-2023-07-26_13.04.54-client.txt)

Game Version: 1.19.2
Mod Loader: Forge 43.2.20
Both 1.1.1 and 1.1.0 versions of Mystic Potions causes the crash.

**Comment by creep3rcrafter** [comment]
Sent a msg to the owner of Dynamic Mining to see if he had a repository to hopefully see what the issue is.

**Comment by creep3rcrafter** [comment]
hopefully fixed it with the latest versions

**Comment by JuicyCosmos** [comment]
Appears to be fixed with the latest versions after a bit of testing. I'll close the issue for now. Anyway thanks!
